### PR TITLE
add possibility to send encrypted Web Push Payload to chrome browser

### PR DESCRIPTION
**Pull request by marcelloceschia**
documentation about Web Push Payload Encryption: https://developers.google.com/web/updates/2016/03/web-push-encryption

### CODE REVIEW

**Comment by pdincau** [comment]
hi @marcelloceschia , can you make the build pass so that i can integrate?

**Comment by marcelloceschia** [comment]
Yes, I will fix this on the weekend

**Comment by marcelloceschia** [comment]
Hello @pdincau sorry for being late for this request.
I have fixed the dialyzer issues and ci is now passed

**Comment by pdincau** [comment]
Merged. Thanks

**Pull request merged**
